### ISSUE TITLE
429 Errors

### ISSUE THREAD

**Issue by MikeTheDead** [instaagroup/instaadownload#4]
It worked well for me at first. but ive recently encountered 429 errors for too many requests and it hasn't gone away. Is there a fix for this?

**Comment by vyrzdev** [comment]
The HTTP *429 Too Many Requests* response status code indicates the user
has sent too many requests in a given amount of time ("rate limiting").

A Retry-After
<https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After> header
might be included to this response indicating how long to wait before
making a new request.

**Comment by vyrzdev** [comment]
The *HTTP 429 Too Many Requests* response status code indicates the user
has sent too many requests in a given amount of time ("rate limiting").

A [Retry-After](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) header might be included to this response indicating how long to wait before making a new request.


Essentially Instagram is rate limiting your bot, and the only way to fix it is to try to change your IP address... This isn't the kind of thing that you should put in a GitHub issue, and it would be a good idea to close this issue.

**Comment by MikeTheDead** [comment]
Ok, Thank you
