### ISSUE TITLE
I keep getting errors

### ISSUE THREAD

**Issue by Krizsan0596** [instaagroup/instaadownload#7]
So I don't know if you guys are still checking these, but if yes, could you please help?
I've set everything up as you say, except for urllib3 as it says requests needs a previous version. When I start the script, it gives me a 405 error, then says login successful. When I try to message the bot, it gives me a 400 error and says "message: Text is missing.".
I don't really expect to get a reply, but I would be grateful if someone could help me!

**Comment by dome272** [comment]
Join the discord: https://discord.gg/PD5rV93mpx and ask your question there. A lot of people still have running Instagram Downloaders and they probably can help you.
